---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-sample
  labels:
    app: helm-app
    test: test
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.example-app: "semver: >=1.0.1, <1.0.9"
    
spec:
  selector:
    matchLabels:
      app: helm-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: helm-app
    spec:
      containers:
      - name: helm-sample
        image: chandu054/fluxcd-demo:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
